"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NumbersCollection_1 = require("./NumbersCollection");
var numbresCollection = new NumbersCollection_1.NumbersCollection([50, 3, -5, 0]);
numbresCollection.sort();
console.log(numbresCollection.data);
//  const charactersCollection = new CharactersCollection('ananyX');
//  charactersCollection.sort();
// console.log(charactersCollection.data);
// const numbersCollection =new NumbersCollection([50,3,-5,0]);
// numbersCollection.sort();
// const linkedList=new LinkedList();
// linkedList.add(500);
// linkedList.add(-10);
// linkedList.add(-3);
// linkedList.add(-4);
// linkedList.sort();
// linkedList.print();
